Repository best-cat-hustlers/cs446-project, pull requests merged in 2019-06, with the labels that each got.

#7 Add MultiplayerMenu, Lobby, and Join pages
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/bestCatHustlers/sukodublitz/JoinActivity.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/LobbyActivity.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/MultiplayerMenuActivity.java
  app/src/main/res/layout/activity_join.xml
  app/src/main/res/layout/activity_lobby.xml
  app/src/main/res/layout/activity_multiplayer_menu.xml
  app/src/main/res/values/strings.xml
Labels: chore

#8 Create Game And Results Pages
  .idea/codeStyles/Project.xml
  .idea/compiler.xml
  .idea/copyright/profiles_settings.xml
  .idea/encodings.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/bestCatHustlers/sukodublitz/GameActivity.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/ResultsActivity.java
  app/src/main/res/layout/activity_game.xml
  app/src/main/res/layout/activity_results.xml
Labels: chore

#10 Connect All Pages Into One Flow
  app/src/main/java/com/bestCatHustlers/sukodublitz/GameActivity.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/GameSetupActivity.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/GameSetupActivityPresenter.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/JoinActivity.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/LobbyActivity.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/MainActivity.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/MainActivityPresenter.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/MainSettingsActivity.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/MultiplayerMenuActivity.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/ResultsActivity.java
  app/src/main/res/layout/activity_lobby.xml
  app/src/main/res/layout/activity_multiplayer_menu.xml
Labels: feature

#24 Display Game Board
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/bestCatHustlers/sukodublitz/BoardGame.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/GameActivity.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/GameSetupActivity.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/LobbyActivity.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/ResultsActivity.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/game/GameActivity.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/game/GameBoardView.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/game/GameContract.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/game/GamePresenter.java
  app/src/main/res/drawable/background_gradient_red_blue.xml
  app/src/main/res/layout/activity_game.xml
Labels: feature

#30 Adapt Board View Size To Parent
  app/src/main/java/com/bestCatHustlers/sukodublitz/game/GameBoardView.java
  app/src/main/res/layout/activity_game.xml
Labels: bug

#28 Chore/setup main settings
  app/src/main/java/com/bestCatHustlers/sukodublitz/GameSetupActivity.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/GameSetupActivityPresenter.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/GameSetupContract.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/GameSetupPresenter.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/MainActivity.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/MainActivityPresenter.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/MainSettingsActivity.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/MainSettingsContract.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/MainSettingsModel.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/MainSettingsPresenter.java
  app/src/main/res/layout/activity_game_setup.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_main_settings.xml
  app/src/main/res/values/strings.xml
Labels: chore

#37 Fix back button and add UI for button on Lobby page
  app/src/main/res/drawable/background_gradient_red_blue.xml
  app/src/main/res/drawable/button_long_special.xml
  app/src/main/res/drawable/ic_chevron_left_black.xml
  app/src/main/res/drawable/ic_chevron_left_black_24dp.xml
  app/src/main/res/values/styles.xml
Labels: feature

#41 Match Multiplayer, Join and Lobby pages to the design
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/bestCatHustlers/sukodublitz/MainActivityPresenter.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/join/JoinActivity.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/join/JoinPresenter.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/lobby/LobbyActivity.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/lobby/LobbyPresenter.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/multiplayer/MultiplayerMenuActivity.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/multiplayer/MultiplayerMenuPresenter.java
  app/src/main/res/layout/activity_join.xml
  app/src/main/res/layout/activity_lobby.xml
  app/src/main/res/layout/activity_multiplayer_menu.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feature

#45 Add message sender to AI that happens every time AI makes a move
  app/src/main/java/com/bestCatHustlers/sukodublitz/GameAI.java
Labels: chore

#39 Allow Players To Enter Solutions
  app/build.gradle
  app/src/main/java/com/bestCatHustlers/sukodublitz/game/GameActivity.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/game/GameBoardView.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/game/GameContract.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/game/GamePresenter.java
  app/src/main/res/layout/activity_game.xml
  app/src/main/res/values/styles.xml
Labels: feature

#49 Add settings button UI element and tweaks the styles for round buttons
  app/src/main/res/drawable/button_round.xml
  app/src/main/res/drawable/ic_settings_black.xml
  app/src/main/res/layout/activity_join.xml
  app/src/main/res/layout/activity_lobby.xml
  app/src/main/res/layout/activity_multiplayer_menu.xml
  app/src/main/res/values/styles.xml
Labels: feature

#59 Add Player Scores And Timer To Game
  app/src/main/java/com/bestCatHustlers/sukodublitz/game/GameActivity.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/game/GameContract.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/game/GamePresenter.java
  app/src/main/res/layout/activity_game.xml
  app/src/main/res/values/styles.xml
Labels: feature

#67 Update Team Member Roles
  app/src/main/res/values/strings.xml
Labels: chore

#63 Polish main menu layout to reflect settings UI element change
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: feature

#62 Polish Game Setup and add radio button element
  app/src/main/java/com/bestCatHustlers/sukodublitz/GameSetupActivity.java
  app/src/main/res/drawable/radio_button_background.xml
  app/src/main/res/drawable/radio_button_not_selected.xml
  app/src/main/res/drawable/radio_button_selected.xml
  app/src/main/res/layout/activity_game_setup.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: feature

#61 Polish UI for Result Page
  app/src/main/java/com/bestCatHustlers/sukodublitz/results/ResultsActivity.java
  app/src/main/res/layout/activity_results.xml
Labels: feature

#72 Add Simple Game AI And Time Elapsed Results
  app/src/main/java/com/bestCatHustlers/sukodublitz/GameAI.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/game/GameActivity.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/game/GamePresenter.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/results/ResultsActivity.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/results/ResultsContract.java
  app/src/main/java/com/bestCatHustlers/sukodublitz/results/ResultsPresenter.java
Labels: feature
